### ISSUE TITLE
Please add my tool :)

### ISSUE THREAD

**Issue by vanasoft23** [CatTanker/cnc_map_tool_guide#1]
https://github.com/vananasun/yr-maptool

**INI merger!!** (i use it for "compiling" my map automatically with different "modules")
Map renamer
Map preview extractor/encoder

**Comment by CatTanker** [comment]
Please make a pull request, using a similar format to what's already committed to main, and shout if there's a permission issue

**Comment by CatTanker** [comment]
Added
