### ISSUE TITLE
Wrong link in resources

### ISSUE THREAD

**Issue by MahBoiDeveloper** [CatTanker/cnc_map_tool_guide#5]
[Resources](https://cc-resource-docs.readthedocs.io/resources/) page has wrong [link](https://github.com/CatTanker/cnc_map_tool_guide/blob/314670a61142dffe446c3ca243c01e8b1967c644/docs/resources.md?plain=1#L15) to the YosefAnan tutorial playlist. Please, remove second `h` from `https`.

![image](https://github.com/CatTanker/cnc_map_tool_guide/assets/61310813/17e3724c-de72-4d7e-b19c-7002d34ac9b5)

**Comment by CatTanker** [comment]
Thanks for reporting this. Issue fixed.
